version: '3'

services:
  web:
    image: nginx
    ports: 
      - "443:443"
    volumes: 
      - ./nginx:/etc/nginx/conf.d
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=d0th4ck
      - POSTGRES_DB=pgdb
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=d0th4ck